<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs = "unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" />
                            <xs:element name="precio" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="fecha" />
                            <xs:element name="autor" />
                            <xs:element name="capitulo" maxOccurs="2" />
                        </xs:sequence>
                        <xs:attribute name="precio" type="xs:string" />
                        <xs:attribute name="paginas" type="xs:integer" use= "required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
