<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="menu" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entrante" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="principal" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="postre" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="ingredientes" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="precio" type="xs:string" />
                        </xs:sequence>
                            <xs:attribute name="m" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>